apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: dXNlcg==   # base64 encoded "user"
  SPRING_DATASOURCE_PASSWORD: dXNlcnBhc3N3b3Jk   # base64 encoded "userpassword"
