apiVersion: v1
kind: Secret
metadata:
  name: springboot-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: bXl1c2Vy  # Base64 encoded value of 'user'
  SPRING_DATASOURCE_PASSWORD: bXlwYXNzd29yZA==  # Base64 encoded value of 'userpassword'

