apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
spec:
  generators:
    - git:
        repoURL: 'https://github.com/skenguva/Springboot-app.git'
        revision: kubernetes
        directories:
          - path: 'nginx/overlays/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/skenguva/Springboot-app.git'
        targetRevision: kubernetes
        path: 'nginx/overlays/{{path.basename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
