apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx_deploy.yml
  - service.yaml

patches:
  - path: values.yaml
    target:
      kind: Deployment
      name: nginx


