apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Replacing 'bases' with 'resources'
resources:
  - ../../base

# Replacing 'patchesStrategicMerge' with 'patches'
patches:
  - values.yaml

